# MySQL Database Credentials
database:
  user: 'bibliothek'
  password: 'bibliothek1234'
  host: 'mariadb'
  port: 3306
  name: 'bibliothekssoftware'

# Application Settings
application:
  host: '0.0.0.0'
  port: 4567
