# MySQL Database Credentials
database:
  user: 'user'
  password: 'S3curePassw0rd'
  host: 'localhost'
  port: 3306
  name: 'bibliothek'

# Application Settings
application:
  host: 'localhost'
  port: 4567
