version: "3"
services:

### MariaDB Container #######################################

    mariadb:
      image: mariadb:10.1
      ports:
        - "127.0.0.1:3306:3306"
      environment:
        MYSQL_DATABASE: bibliothekssoftware
        MYSQL_ROOT_PASSWORD: root1234
        MYSQL_USER: bibliothek
        MYSQL_PASSWORD: bibliothek1234
      volumes:
      - ./data/mysql:/var/lib/mysql
      - ./table-struct-demo.sql:/docker-entrypoint-initdb.d/init.sql

### Bibliothekssoftware Container ##########################################

    bibliothek:
      image: fhl-swt1/bibliothek
      volumes:
        - ./data/bibliothek/application.yaml:/code/application.yaml
      depends_on:
        - mariadb
      ports:
        - "127.0.0.1:4567:4567"